services:
  odoo-communitypackage-db:
    container_name: odoo-communitypackage-db
    image: postgres:16
    environment:
      POSTGRES_USER: odoocommunitypackage
      POSTGRES_PASSWORD: odoocommunitypackage
      POSTGRES_DB: odoocommunitypackage
    volumes:
      - odoo-cp-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoocommunitypackage -d odoocommunitypackage"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  odoo-communitypackage-web:
    container_name: odoo-communitypackage-web
    image: odoo:18
    depends_on:
      odoo-communitypackage-db:
        condition: service_healthy
    ports:
      - "9098:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo-cp-web-data:/var/lib/odoo
    restart: unless-stopped

volumes:
  odoo-cp-db-data:
  odoo-cp-web-data:
