[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = odoo-communitypackage-db
db_port = 5432
db_user = odoocommunitypackage
db_password = odoocommunitypackage
db_name = odoocommunitypackage
admin_passwd = admin
dbfilter = ^odoocommunitypackage$
list_db = False
log_level = info
without_demo = False
